# Site wide configuration

title: "underdeveloped"
description: "A perpetual work-in-progress."
logo: # 120x120 px default image used for Twitter summary card
teaser: phold.png
locale: en
#url: http://localhost:4000
#feed:
  #path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: Avery Horton
  email: avghdev@gmail.com   
  twitter: avghdev
  google:
    ad-client:
    ad-slot:
  bio: "one curious man"
  avatar: me.jpg # 160x160 px image for author byline
  disqus-shortname: underdeveloped


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
